package majestella.core.prototype.mvp;

public enum AppViewType {
  START, MAIN_NAVIGATION, SERVICE_SELECTION, LOCATION_MAIN, WISH_LIST, LOCATION_SETTING, 
  LOCATION_INFO, SERVICE_DETAILS, ROOM_SERVICE, ROOM_SERVICE_CARD, HOTEL_RESTAURANT, HOTEL_SPA, 
  SETTING, 
  
  
  LOGIN, FOOTER_WIDGET, HEADER_WIDGET, SHARE, SIGNUP, USER, ITEM_WIDGET, PHOTO_EDITOR,
  EDIT_BAR_WIDGET, EDITOR_FOOTER_WIDGET, STICKER_SELECT, STICKER_INDEX_WIDGET, STICKER_PREVIEW_WIDGET,
  BASE, LOADVIEW;
}
